SELECT PROJECT.NAME AS PROJECT, TEST.NAME AS TEST, TEST.MIN_WORKING_TIME
FROM 
(SELECT PROJECT_ID,NAME, MIN(DATEDIFF(millisecond,START_TIME,END_TIME)) AS MIN_WORKING_TIME  
         FROM UNION_REPORTING.TEST GROUP BY NAME) AS TEST
JOIN
 (SELECT  NAME, ID 
         FROM UNION_REPORTING.PROJECT) AS PROJECT
ON TEST.PROJECT_ID = PROJECT.ID
ORDER BY PROJECT.NAME, TEST.NAME
 LIMIT 100