SELECT PROJECT.NAME AS PROJECT,TEST.NAME AS TEST,TEST.START_TIME AS DATE FROM UNION_REPORTING.PROJECT AS PROJECT 
JOIN 
UNION_REPORTING.TEST AS TEST
ON PROJECT.ID = TEST.PROJECT_ID
WHERE TEST.START_TIME > '2015-11-07'
ORDER BY PROJECT.NAME,TEST.NAME
LIMIT 100
